"""Initial migration

Revision ID: 19e1ed64cd90
Revises: 904c17bb3624
Create Date: 2025-11-05 15:14:56.296000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e1ed64cd90'
down_revision = '904c17bb3624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suburbs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('suburbs_suburb_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suburbs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('suburbs_suburb_key'), ['suburb'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
