"""1

Revision ID: 904c17bb3624
Revises: 
Create Date: 2025-11-04 22:33:23.931000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904c17bb3624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('suburb', sa.String(length=35), nullable=False),
    sa.Column('property', sa.String(length=35), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('bedroom', sa.Integer(), nullable=False),
    sa.Column('toilets', sa.Integer(), nullable=False),
    sa.Column('ensuite', sa.Integer(), nullable=False),
    sa.Column('condi', sa.Integer(), nullable=False),
    sa.Column('carport', sa.Integer(), nullable=False),
    sa.Column('pool', sa.Boolean(), nullable=False),
    sa.Column('furnished', sa.Boolean(), nullable=False),
    sa.Column('cottage', sa.Integer(), nullable=False),
    sa.Column('power', sa.Boolean(), nullable=False),
    sa.Column('pbackup', sa.Boolean(), nullable=False),
    sa.Column('water', sa.Boolean(), nullable=False),
    sa.Column('wbackup', sa.Boolean(), nullable=False),
    sa.Column('gated', sa.Boolean(), nullable=False),
    sa.Column('garden', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=130), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suburbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constituency', sa.String(length=35), nullable=False),
    sa.Column('council', sa.String(length=35), nullable=False),
    sa.Column('suburb', sa.String(length=45), nullable=False),
    sa.Column('density', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suburb')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('suburbs')
    op.drop_table('properties')
    # ### end Alembic commands ###
